# Generated by Django 5.0.6 on 2024-07-12 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
