# Generated by Django 5.0.6 on 2024-07-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_stocks_owner_alter_stocks_name_alter_stocks_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='owner',
        ),
    ]
