# Generated by Django 5.0.6 on 2024-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='reason',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
