# Generated by Django 5.0.6 on 2024-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_money_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
