# Generated by Django 5.0.6 on 2024-07-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_remove_money_budget_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
